name: dart_network
description: Try to call some stuffs from network.

version: 1.0.0+1

dependencies:
  # dson: any # replace for latest version
dev_dependencies:
  build_runner: any
  build_web_compilers: any